### ISSUE TITLE
Nice tool! Congrats for finding a way to use our app :)

### ISSUE THREAD

**Issue by Kinark** [MD5-Hashm/NotchNookAuthEmulator#1]
Congrats on getting access to NotchNook!

I'm NotchNook's creator and I feel happy people are actually running a script in go and making a local proxy for getting access to the app, it means the app is good, they just can't or don't wanna pay for the app.

The people who will use this repo would never buy the app or subscribe, so I won't be fixing this "security flaw". I'm not very interested in protecting the app against piracy. Without piracy I wouldn't be 1% of what I am today. So use at will! lol

Congrats!

**Comment by Kinark** [comment]
If you may, please fix the lo.cafe link in the README.md, usually people don't know `lo.cafe` is an actual URL so yeah lol

**Comment by MD5-Hashm** [comment]
I appreciate you reaching out and I'm glad that I haven't offended you in the sharing of this program. I think that NotchNook is a super cool app and I am excited to see the future of it, I don't have a licence at the moment as I am a student trying to save money but hope to support your work one day. If you ever change your mind and want me to delete this repository let me know, for now I have updated the links to the correct address!
